apiVersion: apps/v1
kind: Deployment
metadata:
  name: sistema-nginx-deployment
spec:
  template:
    metadata:
      name: sistema-nginx
      labels:
        app: sistema-nginx
    spec:
      containers:
        - name: sistema-container
          image: nginx:latest
          ports:
            - containerPort: 80
  replicas: 1
  selector:
    matchLabels:
      app: sistema-nginx
